### ISSUE TITLE
Serial Sampling

### ISSUE THREAD

**Issue by guinwogan** [kern-lab/discoal#1]
I am very interested in using discoal to run simulations for time series data. I would be excited to see serial sampling incorporated so I could analyze samples collected before, during, and after a selective sweep.

**Comment by kern-lab** [comment]
hi there-- after a long wait I believe I have implemented this. the code is still new, so there are bound to be bugs, but check out the ancient_samples branch of the code. once it's been tested I will merge that branch back in to the master
