### ISSUE TITLE
Tree output mode with recombination

### ISSUE THREAD

**Issue by 35ajstern** [kern-lab/discoal#10]
when I simulate in tree mode with vs. without recombination, I get very different trees at the selected site: (simulating partial sweep with 1 ancient sample)

(1) no recom (rho=0)
`$ ./discoal 51 1 100000 -t 0 -r 0 -A 1 0 0.5 -x 0.5 -c 50e-2 -ws 0 -a 200 -N 10000`

(2) with recom (rho=1)
` $ ./discoal 51 1 100000 -t 0 -r 1 -A 1 0 0.5 -x 0.5 -c 50e-2 -ws 0 -a 200 -N 10000
`
The trees without recom (1) look normal. But (2) produces local trees that have very long terminal branches; e.g. 

`(((14:1.426351,(3:1.417362,7:1.417362):0.008989):0.001227,(((42:0.770007,(2:0.718529,(21:0.701219,8:0.701219):0.017310):0.051478):0.041590,(((22:0.721283,46:0.721283):0.030267,(((49:0.715397,(36:0.702613,(12:0.700720,30:0.700720):0.001893):0.012785):0.003924,(9:0.711552,(16:0.709964,(18:0.705181,11:0.705181):0.004783):0.001588):0.007770):0.013743,(40:0.719578,44:0.719578):0.013486):0.018486):0.010561,((48:0.708968,19:0.708968):0.033373,24:0.742341):0.019770):0.049486):0.057823,(((20:0.803319,29:0.803319):0.003727,26:0.807046):0.021534,6:0.828580):0.040839):0.558159):0.073415,(0:0.627141,((27:0.667150,((13:0.563922,(33:0.559686,43:0.559686):0.004236):0.018902,(((((39:0.551358,28:0.551358):0.005595,(32:0.553924,(17:0.549684,4:0.549684):0.004241):0.003029):0.009503,(5:0.558221,38:0.558221):0.008236):0.000828,31:0.567285):0.003854,((37:0.547439,(45:0.546483,23:0.546483):0.000957):0.007550,(35:0.551138,(50:0.550607,(41:0.544904,1:0.544904):0.005703):0.000532):0.003851):0.016149):0.011686):0.084326):0.123691,((10:0.547810,15:0.547810):0.053473,((34:0.546782,47:0.546782):0.031666,25:0.578448):0.022836):0.189558):0.336300):0.373851);`

which looks like this when i plot it in Dendroscope:

<img width="582" alt="screen shot 2018-09-08 at 1 46 45 pm" src="https://user-images.githubusercontent.com/20346545/45258501-a53f5b00-b36d-11e8-9c0a-6041eeddaaf8.png">

**Comment by andrewkern** [comment]
there was a bug in the routine I had written to output newick trees that led to this issue with bad times. the latest patch on master should fix this issue. @35ajstern please take a look and let me know if it looks good. Thanks for finding the bug!

**Comment by 35ajstern** [comment]
You're the man for fixing this on short notice, Andy. Thanks! --Aaron
