### ISSUE TITLE
Error: trajectory too bigly

### ISSUE THREAD

**Issue by SBNoor** [kern-lab/discoal#14]
I running simulations provided by the article 'soft sweeps are the dominant mode of adaptation in the human genomes'. I am using PEL population as an example. However when I run the command (provided in the supplementary material), the script runs for a while and then ends with the following error:

**trajectory too bigly. step= 500000000 freq = 0.015251. killing myself gently**

The command I ran is:

./discoal 170 50 200000 -Pt 40 400 -Pre 183.333 550 -en 0.0511027 0 0.901143 -en 0.083915 0 0.864485 -en 0.122773 0 1.06039 -en 0.168789 0 1.58688 -en 0.223285 0 2.81673 -en 0.28782 0 4.82159 -en 0.364248 0 7.19025 -en 0.454755 0 9.06247 -en 0.561862 0 9.83074 -en 0.688627 0 9.70829 -en 0.838705 0 8.64111 -en 1.01638 0 7.26809 -en 1.22674 0 6.05683 -en 1.47579 0 5.23362 -en 1.77063 0 4.74448 -en 2.11971 0 4.47973 -en 2.53297 0 4.39674 -en 3.02225 0 4.42625 -en 3.60152 0 4.6542 -en 4.2873 0 5.13193 -en 5.09922 0 6.01236 -en 6.06048 0 7.34732 -en 7.1985 0 8.79895 -en 8.5458 0 9.64914 -en 10.1409 0 9.63931 -en 12.0294 0 8.66812 -ws 0 -Pa 41.6667 833.333 -Pu 0 0.12 -Pf 0 0.2 -x 0.5

Could you tell me why am I getting this error? I am using the same command as mentioned in the article. The only difference is number of replicates. Also, the commands run fine for hard sweeps. It is for soft sweeps, I'm getting this error.

**Comment by andrewkern** [comment]
you are getting this error because discoal was compiled (by default) with a hard coded step size trajectory size that is too small for the model you are trying to simulate. In the file `discoal.h` you can increase the `define` on line 119 to a larger number, recompile, and try again.
