### ISSUE TITLE
maxmuts

### ISSUE THREAD

**Issue by rebzzy** [kern-lab/discoal#4]
Hi - 
I'm interested in using the program and was testing it out using the code provided in the shic paper. I can get the equilibrium neutral models to produce output but I get an error when trying to run the Tennessen models. From your supplemental table: 
`discoal_multipop  170 1000 110000 -Pt 10560 31680 -r 17600`
The error I get is 
`Assertion failed: (size < MAXMUTS), function makeGametesMS, file discoalFunctions.c, line 2048.
Abort trap: 6`
I tried recompiling discoal with a larger value of MAXMUTS but that didn't help. Do you have any suggestions?
Thanks!

**Comment by kern-lab** [comment]
Hi there-- quick question before I start digging too deep here: did you run this with the associated demographic as well (i.e. the series of "-en" flags)?

**Comment by rebzzy** [comment]
Ah no - that works. Sorry to bother you!

**Comment by kern-lab** [comment]
okay great! In general there could be cases when 4Nu gets really big where the MAXMUTS assert could get tripped and recompiling would be necessary, but I wouldn't suggest simulating those with discoal.
