### ISSUE TITLE
Can discoal simulate non-random mating such as inbreeding/selfing?

### ISSUE THREAD

**Issue by oushujun** [kern-lab/discoal#5]
Hello,

I have a question: Can discoal simulate non-random mating such as inbreeding/selfing?

I could not find a coalescence simulator that has such functions. Not sure if this is limited by the theory or people just forgot about it...

Thanks!

Shujun

**Comment by kern-lab** [comment]
No discoal is not set up to simulate selfing situations

**Comment by oushujun** [comment]
Is it possible to add this feature like forward simulators do?

**Comment by kern-lab** [comment]
This is not a feature that I will be adding in the foreseeable future but as the code is open source you can certainly add it yourself.
