### ISSUE TITLE
Questions in scaled parameter settings

### ISSUE THREAD

**Issue by oushujun** [kern-lab/discoal#7]
Dear Andrew,

I was trying to use `discoal` to simulate data to feed `diploS/HIC`, I have read the manual carefully and also the `Kern and Schrider 2018` paper. However, I still not sure about the setting of population parameters. The manual mentioned the mutation rate `u`, recombination rate `p`, and selection coefficient `s` are scaled by `4N0` where `N0` is the most recent (current) effective population size. However, I could not find a clear statement of the units of `u`, `p`, and `s` themselves - are they in the units of per generation **per length of the simulated locus** instead of per generation **per bp**?

In the `Table S1` of the `Kern and Schrider 2018` paper, the mutation rate and recombination rate were scaled by `4NL` and `4NrL`, respectively, where `L` is the length of the simulated chromosome. However, the selection coefficient was scaled by `2Ns`, where the unit of `s` is not given. These seem to be not consistent with the manual. Could you please clarify these three parameters?

For the simulation of the mosquito case, a very short time of selection were simulated with `4N0T` = 0.000040 where T is the generation backward from the present. Is it set for the purpose of capturing the recent soft sweep of the _Gste_ locus? Does `diploS/HIC` have power to detect ancient sweeps (eg. 10,000 generations ago) given the corresponding training set?

The time setting for demographic changes is also not clear to me. From the manual, I learn that -en specify the time in unit of `4N0`, so if I have `N0` = 2500, then `-en 0.5 0 0.1` means at generation 5000 (4\*2500\*0.5), pop 0 has a shrinkage of `Ne` to 10%? Does this time count backward from the present or forward from some point? If it's backward, then the example given in the manual `-en 0.5 0 0.1 -en 1.2 0 0.8` should be explained as the population has a shrinkage to 80% in the time of 1.2 (older) and further shrunk to 10% in the time of 0.5 (closer to the present), but not as in the manual "at time 0.5 the population crashes to 10% of its initial size and then at time 1.2 it rebounds to 80% of its initial size.". Please help to clarify.

Thank you very much in advance!

Shujun

**Comment by andrewkern** [comment]
discoal scales all parameters by `4N` or `2N` as appropriate. Thus the user sets \rho, which is equivalent to `4Nr` where r is the rate per locus per generation. The same would be true for u -- that would be the mutation rate per locus per generation

**Comment by oushujun** [comment]
Thank you for the clarification. Shujun

**Comment by rileycorcoran** [comment]
Hello, I have a similar confusion to Shujun about creating these parameters, and I was hoping you could provide more clarification. Would you be able to give a step-by-step calculation of how you go from single values to the parameters included in a discoal simulation? For example, mutation rate: what exact calculation did you use to get to the parameter used in Table S1 from Kern and Schrider 2018: `Burkino Faso Demography (moderate selection) - ~U(1750.2, 17502.0`)? If I have a mutation rate per base pair ($\mu$), would I multiply it by 4 * population size * the number of sites I am simulating to get my parameter (i.e. `-t` $\theta$ where $\theta = 4N_0*\mu*nSites$)? 

Also, does it matter what units the recombination rate r value is in (`-r` $\rho$ where $\rho = 4N_0\*r\*nSites$), assuming that $r$ is the variable for a normal reported recombination rate (e.g. 2.1cM/Mb)?

Similarly, I am also struggling to understand the time parameter (used for both `-en` and `-ws`). Knowing that time is in "units of $4N_0$ generations", am I right in saying that the calculation to get that parameter, starting with knowing I'm looking $N$ generations ago, would be parameter = $\frac{N\ gens\ ago}{4N_0}$? Or is it parameter = $(N\ gens\ ago) * 4N_0$, similar to other parameters that seem to be obtained by multiplying by $4N_0$ (or something completely different)?

I'm sorry if this is confusing, I am just struggling trying to figure out how to get from normal values like population size or mutation rate to the parameters needed for discoal, so any help in interpreting this would be appreciated. Thank you!
